if has("gui_macvim")

  " command-T on macvim :)
  macmenu File.New\ Tab key=<nop>
  nmap <D-t> :CommandTFlush<CR>:CommandT<CR>
  imap <D-t> <ESC>:CommandTFlush<CR>:CommandT<CR>


  " Command-Return for fullscreen
  macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-CR>


  " Command-Shift-F for Ack
  map <D-F> :Ack <C-R>=expand("<cword>")<CR>
  vmap <D-F> :Ack <C-R>=expand("<cword>")<CR>

  " Command-/ to toggle comments
  map <D-/> <plug>NERDCommenterToggle
  imap <D-/> <Esc><D-/>i


  " Command-][ to increase/decrease indentation
  vmap <D-]> >gv
  vmap <D-[> <gv


  " Map Command-# to switch tabs
  map  <D-1> 1gt
  imap <D-1> <Esc>1gt
  map  <D-2> 2gt
  imap <D-2> <Esc>2gt
  map  <D-3> 3gt
  imap <D-3> <Esc>3gt
  map  <D-4> 4gt
  imap <D-4> <Esc>4gt
  map  <D-5> 5gt
  imap <D-5> <Esc>5gt
  map  <D-6> 6gt
  imap <D-6> <Esc>6gt
  map  <D-7> 7gt
  imap <D-7> <Esc>7gt
  map  <D-8> 8gt
  imap <D-8> <Esc>8gt
  map  <D-9> 9gt
  imap <D-9> <Esc>9gt

  " switch to previous tab using CMD-0
  let g:lasttab = 1
  nmap <D-0> :exe "tabn ".g:lasttab<CR>
  au TabLeave * let g:lasttab = tabpagenr()

  " Start without the toolbar
  set guioptions-=T

  "Run tests Ruby/Rails
  "All tests: CMD-R
  autocmd User Rails imap <D-r> <ESC>:Rake<CR>
  autocmd User Rails nmap <D-r> :Rake<CR>

  "Single test: CMD+SHIFT+R
  autocmd User Rails imap <D-R> <ESC>:.Rake"<CR>
  autocmd User Rails nmap <D-R> :.Rake"<CR>

  "CMD+SHIFT+T to open tagbar
  macmenu File.Open\ Tab\.\.\. key=<nop>
  map <D-T> :TagbarOpen<CR>
  imap <D-T> <ESC><D-T>i

  "Reload .gvimrc when saved
  autocmd BufWritePost .vimrc source %
  autocmd BufWritePost .vimrc source ~/.gvimrc
  autocmd BufWritePost .gvimrc source %

endif
