desc "Install zsh config"
task :zsh do
  puts "** Installing zsh config..."
  my_symlink('zshrc', __FILE__, '~/.zshrc')
  my_symlink('zshenv', __FILE__, '~/.zshenv')

  FileList["#{File.dirname(__FILE__)}/zsh.d/lib/*.zsh"].each do |f|
    f.gsub!(/^\.\//, '')
    my_symlink("../#{f}", __FILE__ , "~/.#{f}")
  end

  FileList["#{File.dirname(__FILE__)}/zsh.d/completion/*"].each do |f|
    f.gsub!(/^\.\//, '')
    my_symlink("../#{f}", __FILE__ , "~/.#{f}")
  end
end

task :install => :zsh
