#!/bin/zsh
###
# setup exports
###

export PATH=$HOME/bin:/opt/local/bin:/opt/local/sbin:/opt/local/libexec/gnubin:/opt/local/lib/postgresql84/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin

export MANPATH=/opt/local/share/man:$MANPATH		# macports man

export PATH=$PATH:/usr/texbin

export HOSTNAME="`hostname`"

if [[ -s $HOME/.rvm/scripts/rvm ]] ; then source $HOME/.rvm/scripts/rvm ; fi

export JAVA_OPTS='-d32 -client'

