#!/bin/zsh

if [ -z "$PS1" ]; then
  return
fi

for config_file (~/.zsh/zsh.d/lib/*.zsh); do
  source $config_file
done

for i in $HOME/projects/*/*; do
  dir=$i:t
  hash -d $dir=$i
done

function releng(){
	dir=`ls -d *releng* 2>/dev/null`
	if [[ -d "$dir" ]]; then
		cd $dir
	fi
}

function mvim() {
  (unset GEM_PATH GEM_HOME; command mvim "$@")
}

### Added by the Heroku Toolbelt

export PATH="/usr/local/heroku/bin:$PATH"
